### ISSUE TITLE
holla()

### ISSUE THREAD

**Issue by rgbkrk** [thejameskyle/babel-plugin-ken-wheeler#1]
In great @kenwheeler JavaScript style, I'd love to see holla as the keyword for functions.

```js
holla shout(x) { console.log(x) }
```

Alternatively, Ken may choose to lexically bind `this`:

```js
holla(x) => { console.log(x) }
```

Either way, I'd love to be able to holla back.

**Comment by thejameskyle** [comment]
I'm afraid I can't change keywords in Babel

**Comment by rgbkrk** [comment]
I feel way less bad about not being able to figure it out on my own now.
